# Global variables for controlling scenario execution

# PoC1 control
run_poc1: true
poc1_phases:
  - reconnaissance
  - initial-access
  - privilege-escalation
  - persistence
  - action-on-objectives

# PoC2 control
run_poc2: false
poc2_phases:
  - reconnaissance
  - initial-access
  - privilege-escalation
  - persistence
  - action-on-objectives

# PoC3 control
run_poc3: false
poc3_phases:
  - reconnaissance
  - initial-access
  - privilege-escalation
  - persistence
  - action-on-objectives

# Common variables (example IP addresses)
attacker_ip: 192.168.254.130
collector_ip: 192.168.254.131
web_victim_ip: 192.168.254.129
privesc_target_ip: 192.168.254.132

# Collector output file for stolen cookie
collector_cookie_file: /tmp/collector_output.txt

# Optional: Control individual phases in chain role
run_persistence_in_chain: true

# Credentials (for educational purposes only)
ssh_password: "password"
dvwa_admin_password: "evilpass"
ssh_user: "user"

# Cookie values for session hijacking (educational purposes)
stolen_cookie_value: "stolen_session_id_12345"


