---
- hosts: web-victim
  become: yes
  roles:
    - setup-web-victim

- hosts: privesc-target
  become: yes
  roles:
    - setup-privesc-target

- hosts: collector
  become: yes
  roles:
    - setup-collector

- hosts: attacker
  become: yes
  tasks:
    - name: PoC1 – only selected phases
      include_role:
        name: poc1/{{ item }}
      loop: "{{ poc1_phases }}"
      when: run_poc1

    - name: PoC2 – only selected phases
      include_role:
        name: poc2/{{ item }}"
      loop: "{{ poc2_phases }}"
      when: run_poc2

    - name: Chain-Szenario
      include_role:
        name: chain
      when: run_chain
