---
- name: Setup Web Victim
  hosts: web-victim
  become: yes
  tags: setup
  roles:
    - setup-web-victim

- name: Setup Privesc Target
  hosts: privesc-target
  become: yes
  tags: setup
  roles:
    - setup-privesc-target

- name: Setup Collector
  hosts: collector
  become: yes
  tags: setup
  roles:
    - setup-collector

- name: Setup Attacker
  hosts: attacker
  become: yes
  tags: setup
  roles:
    - setup-attacker

- name: Run PoC1 with selected phases
  hosts: attacker
  become: yes
  tasks:
    - name: PoC1 – selected phases
      include_role:
        name: "poc1/{{ item }}"
      loop: "{{ poc1_phases }}"
      when: run_poc1

- name: Run PoC2 with selected phases
  hosts: attacker
  become: yes
  tasks:
    - name: PoC2 – selected phases
      include_role:
        name: "poc2/{{ item }}"
      loop: "{{ poc2_phases }}"
      when: run_poc2

- name: Run PoC3 with selected phases
  hosts: attacker
  become: yes
  tasks:
    - name: PoC3 – selected phases
      include_role:
        name: "poc3/{{ item }}"
      loop: "{{ poc3_phases }}"
      when: run_poc3 or run_chain
