---
- name: Cleanup - Remove uploaded webshells
  file:
    path: /var/www/html/DVWA/hackable/uploads/shell.php
    state: absent
  delegate_to: "{{ groups['web-victim'][0] }}"
  when: cleanup_webshells | default(true)

- name: Cleanup - Remove malicious cron jobs
  shell: "grep -v '@reboot bash -c' /etc/crontab | sudo tee /etc/crontab"
  delegate_to: "{{ groups['privesc-target'][0] }}"
  when: cleanup_persistence | default(true)
  failed_when: false

- name: Cleanup - Remove malicious database entries
  mysql_query:
    login_db: dvwa
    query: "DELETE FROM users WHERE user = 'eviladmin'"
  delegate_to: "{{ groups['web-victim'][0] }}"
  when: cleanup_database | default(true)
  failed_when: false

- name: Cleanup - Stop collector HTTP server
  shell: "pkill -f 'python3 -m http.server 8080'"
  delegate_to: "{{ groups['collector'][0] }}"
  when: cleanup_collector | default(true)
  failed_when: false

- name: Cleanup - Remove collected data files
  file:
    path: /tmp/collector_output.txt
    state: absent
  delegate_to: "{{ groups['collector'][0] }}"
  when: cleanup_data | default(true)

- name: Cleanup - Restart Apache to clear any cached data
  systemd:
    name: apache2
    state: restarted
  delegate_to: "{{ groups['web-victim'][0] }}"
  when: cleanup_services | default(true)

- name: Show cleanup completion message
  debug:
    msg: "Cleanup completed. Systems have been restored to pre-attack state." 