---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install SSH server
  apt:
    name: openssh-server
    state: present

- name: Ensure weak user exists for privilege escalation testing
  user:
    name: user
    password: "{{ 'password' | password_hash('sha512') }}"
    shell: /bin/bash
