- name: Setup DVWA on web-victim
  hosts: web
  become: true
  tasks:
    - name: Install packages
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - git
        state: present
        update_cache: yes

    - name: Clone DVWA repository
      git:
        repo: 'https://github.com/digininja/DVWA'
        dest: /var/www/html/DVWA
        update: yes

    - name: Set permissions
      file:
        path: /var/www/html/DVWA
        owner: www-data
        group: www-data
        recurse: yes
